### ISSUE TITLE
authentication workarounds & fixes

### ISSUE THREAD

**Issue by samjtro** [go-schwab/trader#70]
### what happened?

2024/11/04 21:19:56 listen: listen tcp :443: bind: permission denied

### what did you expect to happen?

n/a

**Comment by samjtro** [comment]
this needs to be fixed ASAP, working on it now

**Comment by samjtro** [comment]
this issue is caused from linux not being able to non-sudo open ports under 10..

might be able to use CAP_NET_BIND_SERVICE as a workaround, currently specifying port via the oauth package breaks so im not sure what the solution is as of right now.

`setcap 'cap_net_bind_service=+ep' /path/to/program`

**Comment by samjtro** [comment]
i think this might be caused due to my firewall configuration, need to retest on another machine

**Comment by leoneu** [comment]
I'm having the same problem on Ubuntu Linux.

**Comment by samjtro** [comment]
10/4, will revert back to the old oauth implementation for the time being while i figure out a solution for us linux users... sorry about that!

**Comment by samjtro** [comment]
@leoneu v0.9.1 is working on linux!

**Comment by samjtro** [comment]
reopened in case you run into any errors. tested on debian and it works, let me know if you run into anything!

**Comment by leoneu** [comment]
works on ubuntu too. However, after entering the schwab password I get redirected to https://127.0.0.1/?code=... I get a refused to connect. page.

**Comment by samjtro** [comment]
yep, that should be the normal behavior!

just to clarify, once you copy and paste tha url into the terminal it works as expected?

**Comment by leoneu** [comment]
This is what I see on the terminal after I login to schwab:

```
Log into your Schwab brokerage account. Copy Error404 URL and paste it here: 2024/11/17 14:56:08 [fatal] invalid token - please reinitiate with 'Initiate'
FAIL
```

**Comment by samjtro** [comment]
could you remove the '.json' file in your program directory and reinitiate, and let me know if it give you the same error?

**Comment by samjtro** [comment]
could you share your code with me actually @leoneu ? there's a few places it could be occurring from but i want to double check.

**Comment by samjtro** [comment]
@leoneu based on your suggestions, i've made cleanup of the .json file much more strict; you shouldn't even notice it exists now :)

the main error was originating from the weird complexity of my code; moved really quickly and wrote some strange stuff, cleaned everything up and it should now work as intended.

upgrade to v0.9.2 and let me know how it works!

**Comment by leoneu** [comment]
I got a bit more detail now but still failed. Here are the details. 

fins.go
```
package fins

import (
	"log"

	"github.com/go-schwab/trader"
)

func GetQuote(agent *trader.Agent) trader.Quote {
	quote, err := agent.GetQuote("GOOG")
	if err != nil {
		// Uh-oh.
		log.Fatal(err)
	}
	return quote
}

```
fins_test.go
```
package fins_test

import (
	"testing"

	"github.com/go-schwab/trader"
	"github.com/leoneu/kolekt/fins"
)

func TestQuote(t *testing.T) {

	agent := trader.Initiate()

	q := fins.GetQuote(agent)
	t.Log(q)
}

```

The error:

```
Log into your Schwab brokerage account. Copy Error404 URL and paste it here: 2024/11/19 10:53:15 [err] something went wrong - reinitiating ...
Log into your Schwab brokerage account. Copy Error404 URL and paste it here: --- FAIL: TestQuote (0.52s)
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 20 [running]:
testing.tRunner.func1.2({0x120e4a0, 0xc00001e210})
	/usr/local/go/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1635 +0x35e
panic({0x120e4a0?, 0xc00001e210?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/go-schwab/trader.(*Agent).GetQuote(_, {_, _})
	/home/leo/go/pkg/mod/github.com/go-schwab/trader@v0.9.2/market-data.go:316 +0x6e5
github.com/leoneu/kolekt/fins.GetQuote(_)
	/home/leo/proj/kolekt/fins/fins.go:10 +0x6c
github.com/leoneu/kolekt/fins_test.TestQuote(0xc000136820)
	/home/leo/proj/kolekt/fins/fins_test.go:14 +0x2f
testing.tRunner(0xc000136820, 0x129bbb8)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1743 +0x390
FAIL	github.com/leoneu/kolekt/fins	0.537s
FAIL
```

**Comment by samjtro** [comment]
@leoneu unfortunately, with the linux implementation, running tests break the oauth initialization. it is supposed to hang until you submit your URL, but when the testing library executes it, it doesn't wait and attempts to run the command without the authentication present - thus failing.

try out the below workaround and let me know what happens. in the meantime, ill work on getting the new oauth implementation live on linux so you don't have to do any extra work with your testing implementation:

1. move fins_test.go to the directory above
2. re-run `go run .`
3. go through the authorization process, it should then execute your `GetQuote` function
4. move fins_test.go back into your program directory; now that the `.json` file is present, it won't need to initialize

**Comment by leoneu** [comment]
I see, that was the issue! I created a main file for testing and it works. Thanks!

I assume the URL is copied manually because you would need to open the local http service to the Internet to automate the process. I wonder if there is a workaround to avoid the manual step.

**Comment by samjtro** [comment]
that's correct; the long answer is that schwab doesn't (as far as i'm aware) allow specifying the port for the redirect url. this means that attempting to do the exchange on any port other than the default, 443, causes an error on schwab's end. 

on mac/windows, port 443 is valid for an encrypted tls handshake, so it works perfectly fine. linux doesn't allow non-sudo access under 1024 (i think 1024, might be wrong on the last two digits), so we have to manually parse the redirect url.

think i might have figured out a way to do so, but i'm not sure. will try it out when i can, will be travelling the next few days.

**Comment by samjtro** [comment]
closing - let me know if you run into anything else! happy new year!
